# Generated by Django 4.1.7 on 2023-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="link",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="picture",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
