# Generated by Django 4.1.7 on 2023-04-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_document_file_link_url_page_content_picture_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=64)),
                ("is_publish", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_link", models.CharField(max_length=32)),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Chapter",
        ),
    ]
